### ISSUE TITLE
Data markup

### ISSUE THREAD

**Issue by Petilia** [Kazuhito00/YOLOX-Colaboratory-Training-Sample#2]
Hello!

Your code runs and is a good example for others to follow.

Now I'm trying to use my images for training and I get an error.

I would like to know what tool you use for markup and how to do the markup correctly.

**Comment by Kazuhito00** [comment]
What kind of error did you get?
By the way, VoTT is used for annotation of the file included as a sample.

**Comment by Kazuhito00** [comment]
It will close because time has passed.
If you have another problem, please create the issue again.
