### ISSUE TITLE
isatty() not defined error

### ISSUE THREAD

**Issue by bsense-rius** [Kazuhito00/YOLOX-Colaboratory-Training-Sample#6]
Dear Mr Kazuhito00,

Few days ago colab updated jax library, that it is being used by Megvii Yolox Engine. Jax version in colab implements a new function _can_use_color() that checks stdout.isatrty(). Unfortunately lMegvii/yolox/utils/logger.py class StreamToLoguru, that replaces stdout, does not implement isatty() function. So your notebook fails.

I have reported that issue to Megvii (no reaction) and to jax team who actually fixed it. Unfortunately it would take some time since this version is uptaded in colab. Meanwhile you could add something like below to path class StreamLoguru
```
# In a cell
!awk '1;/def flush/{c=3}c&&!--c{print "    def isatty(self): return True"}' \
/content/YOLOX/yolox/utils/logger.py > /content/YOLOX/yolox/utils/logger.tmp \
&& mv /content/YOLOX/yolox/utils/logger.tmp /content/YOLOX/yolox/utils/logger.py

**Comment by Kazuhito00** [comment]
Dear bsense-rius.
Thank you for telling me about isatty ().
Until Megvii-BaseDetection officially supports it, i will take measures using awk of bsense-rius.

```
!awk '1;/def flush/{c=3}c&&!--c{print "    def isatty(self): return True"}' \
/content/YOLOX/yolox/utils/logger.py > /content/YOLOX/yolox/utils/logger.tmp \
&& mv /content/YOLOX/yolox/utils/logger.tmp /content/YOLOX/yolox/utils/logger.py
```

**Comment by FateScript** [comment]
Hello @Kazuhito00 , we fixed this issue in our latest commit. You may check and update now.
Thanks for your great work.

**Comment by Kazuhito00** [comment]
Hello @FateScript , Thank you for quickly modifying the source code.
I've also modified the notebooks in this repository and confirmed that they work.
