### ISSUE TITLE
How to resume training from last checkpoint?

### ISSUE THREAD

**Issue by jmtrutna** [Kazuhito00/YOLOX-Colaboratory-Training-Sample#7]
I'm getting an estimation of 2 days 17 hours to complete 300 epochs on my custom dataset with yolox-nano. (I was able to train a yolov4Tiny model on the same dataset in 12 hrs.  Is this normal?)  Google colab only allows 24 hours of continuous gpu usage... How do I resume training from my last saved weights?

**Comment by Kazuhito00** [comment]
Please ask questions in the original YOLOX repository.
https://github.com/Megvii-BaseDetection/YOLOX
